"""create_event

Revision ID: 9fa894463654
Revises: 03e4b8da24fb
Create Date: 2026-01-12 10:46:38.055966

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlmodel import AutoString


# revision identifiers, used by Alembic.
revision: str = "9fa894463654"
down_revision: str | None = "03e4b8da24fb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event",
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("calendar_id", sa.Uuid(), nullable=False),
        sa.Column("title", AutoString, nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("start_at", sa.DateTime(), nullable=True),
        sa.Column("end_at", sa.DateTime(), nullable=True),
        sa.Column("actual_start_at", sa.DateTime(), nullable=True),
        sa.Column("actual_end_at", sa.DateTime(), nullable=True),
        sa.Column("is_cancelled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["calendar_id"],
            ["calendar.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_event_actual_end_at"), "event", ["actual_end_at"], unique=False
    )
    op.create_index(
        op.f("ix_event_actual_start_at"), "event", ["actual_start_at"], unique=False
    )
    op.create_index(op.f("ix_event_end_at"), "event", ["end_at"], unique=False)
    op.create_index(
        op.f("ix_event_is_cancelled"), "event", ["is_cancelled"], unique=False
    )
    op.create_index(op.f("ix_event_start_at"), "event", ["start_at"], unique=False)
    op.create_index(op.f("ix_event_title"), "event", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_event_title"), table_name="event")
    op.drop_index(op.f("ix_event_start_at"), table_name="event")
    op.drop_index(op.f("ix_event_is_cancelled"), table_name="event")
    op.drop_index(op.f("ix_event_end_at"), table_name="event")
    op.drop_index(op.f("ix_event_actual_start_at"), table_name="event")
    op.drop_index(op.f("ix_event_actual_end_at"), table_name="event")
    op.drop_table("event")
    # ### end Alembic commands ###
